version: "3"

services:
  score-getter:
    container_name: score-getter
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - type: volume
        source: score-getter-volume
        target: /app
      - type: volume
        source: score-getter-output-volume
        target: /var/log/score-getter
    entrypoint: tail -f
    env_file:
      - .env

volumes:
  score-getter-volume:
    name: score-getter-volume
    driver: local
    driver_opts:
      device: ./app
      type: none
      o: bind

  score-getter-output-volume:
    name: score-getter-output-volume
    driver: local
    driver_opts:
      device: ./output
      type: none
      o: bind
